import colors from "tailwindcss/colors";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        "discord-blurple": "#5865F2",
        white: colors.white,
        black: colors.black,
        transparent: "transparent",
        // slate: colors.slate,
        // gray: colors.gray,
        // zinc: colors.zinc,
        // neutral: colors.neutral,
        //  stone: colors.stone,
        // red: colors.red,
        // orange: colors.orange,
        // amber: colors.amber,
        // yellow: colors.yellow,
        // lime: colors.lime,
        // green: colors.green,
        // emerald: colors.emerald,
        // teal: colors.teal,
        // cyan: colors.cyan,
        // sky: colors.sky,
        // blue: colors.blue,
        // indigo: colors.indigo,
        // violet: colors.violet,
        // purple: colors.purple,
        // fuchsia: colors.fuchsia,
        // pink: colors.pink,
        // rose: colors.rose,
      },
    },
    fontFamily: {
      inter: [
        "Inter Variable",
        "Inter",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Noto Sans",
        "Ubuntu",
        "Cantarell",
        "Helvetica Neue",
        "sans-serif",
      ],
      poppins: [
        "Poppins",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Noto Sans",
        "Ubuntu",
        "Cantarell",
        "Helvetica Neue",
        "sans-serif",
      ],
      mono: ["JetBrains Mono Variable", "JetBrains Mono", "ui-monospace"],
    },
  },
  plugins: [],
};
